## Getting Started 

In [1]:
# To get started with NumPy, you need to install it first. You can do it with below 'pip':
# pip install numpy

# Importing NumPy Library into our file
import numpy as np

## NumPy Creating Arrays

In [12]:
# Creating 1-D array
one_d_arr = np.array([1, 2, 3, 4, 5])
print("1D array:", one_d_arr)

# Creating 2-D array
two_d_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:", *two_d_arr)

# Checking array's number of dimensions
print("Number of dimensions:", two_d_arr.ndim)

# Creating arrays with higher dimensions
high_d_array = np.array([1, 2, 3, 4, 5], ndmin=5)
print("high_d_array:", *high_d_array)
print("high_d_array number of dimensions:", high_d_array.ndim)



1D array: ['1' '2' 'a' '4' '5']
2D array: [1 2 3] [4 5 6]
Number of dimensions: 2
high_d_array: [[[[1 2 3 4 5]]]]
high_d_array number of dimensions: 5


## NumPy Array Indexing

In [18]:
arr = np.array(['a', 'b', 'c', 'd'])

# Accessing the first element of the 1D-array
print("First element of the 1D array:", arr[0])

# Accessing the third element of the 1D-array
print("Third element of the 1D array:", arr[2])

arr_2d = np.array([['z', 'y', 'x'], ['a', 'b', 'c']])

# Accessing the first element of the 2D-array, (the first element of the first nested array)
print("First element of the first nested array:", arr_2d[0][0])

# Accessing the third element of the 2D-array, (the second element of the third nested array)
print("Third element of the second nested array:", arr_2d[1][2])

arr_3d = np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']])

# Acessing the last element of the second nested array by using NEGATIVE INDEXING.
print("The last element of the second nested array:", arr_3d[1][-1])

print("The second element of the third nested array:", arr_3d[-1][-2])

First element of the 1D array: a
Third element of the 1D array: c
First element of the first nested array: z
Third element of the second nested array: c
The last element of the second nested array: f
The second element of the third nested array: h


## NumPy Array Slicing

In [34]:
# Taking elements from one given index to another given index.
# We pass slice instead of index like this: [start:end] = [start(inclusive) : end(exclusive)]
# We can also define the step, like this: [start:end:step].

arr = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])

# [start:end] = [start(inclusive) : end(exclusive)]
print("Slicing with startIndex:1 and endIndex:5", arr[1:5]) # Prints out element(1), element(2), element(3), element(4).

# Slicing from a specific index to the end of the array [3: ]
print("Slicing from index 3 to the end of the array:", arr[3: ])

# Slicing from start of the array to a specific index (not included).
print("Slicing from the beginning of the array to index 5:", arr[ :5])

# Slicing with negative indexes
print("Slicing for getting the last two element of the array:", arr[-3 : -1])

# Getting every other elements of the array by using STEP, like this: [start:end:step].
print("Every other elements of the array, starting from index(1):", arr[1:7:2])

# Getting every other elements of the entire array
print("Every other elements of the entire array:", arr[::2]) 

arr_2d = np.array([['z', 'y', 'x', 'p', 'q', 'w'], ['a', 'b', 'c', 'd', 'e', 'f']])

# Slicing element from the second nested array, from index 1 to index 4 (not included).
print("slice elements from index 1 to index 4 from second nested array:", arr_2d[1, 1:4])

Slicing with startIndex:1 and endIndex:5 ['b' 'c' 'd' 'e']
Slicing from index 3 to the end of the array: ['d' 'e' 'f' 'g']
Slicing from the beginning of the array to index 5: ['a' 'b' 'c' 'd' 'e']
Slicing for getting the last two element of the array: ['e' 'f']
Every other elements of the array, starting from index(1): ['b' 'd' 'f']
Every other elements of the entire array: ['a' 'c' 'e' 'g']
slice elements from index 1 to index 4 from second nested array: ['b' 'c' 'd']


## NumPy Data Types

In [41]:
# strings - used to represent text data.
# integer - used to represent integer numbers.
# float - used to represent real numbers. 
# boolean - used to represent True or False.
# complex - used to represent complex numbers.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

arr1 = np.array([1, 2, 3])
print("array datatype:", arr1.dtype)

arr2 = np.array(['a', 'b', 'c'])
print("array2 datatype:", arr2.dtype)

# Defining datatypes
arr3 = np.array([1, 2], dtype='S')
print("array3 datatype:", arr3.dtype)
print(arr3)

# Converting datatypes
arr4 = np.array([1.2, 3.5, 1.5])
arr4_converted = arr4.astype(int)
print("array4 type: (converted from boolean to int)", arr4_converted.dtype)

array datatype: int32
array2 datatype: <U1
array3 datatype: |S1
[b'1' b'2']
array4 type: (converted from boolean to int) int32


## NumPy Copy vs View

In [43]:
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
original_array = np.array([1, 2, 3, 4, 5])
copy_array = original_array.copy() # A new array of arr
original_array[0] = 44 # Modifying the first element of the arr (original array).
print("Original array:", original_array)
print("Copy array:", copy_array)

view_array = original_array.view()
original_array[1] = 55 #Modirying the second element of the original array.
print("Original array:", original_array)
print("View array:", view_array)

Original array: [44  2  3  4  5]
Copy array: [1 2 3 4 5]
Original array: [44 55  3  4  5]
View array: [44 55  3  4  5]


## NumPy Array Shape

In [45]:
# The shape of an array is the number of elements in each dimension.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) # Prints out (2, 4) which means the array has 2 nested arrays (a 2D array) and each sub-array has 4 elements.
# Integers at every index tells about the number of elements the corresponding dimension has.

arr_fived = np.array([1, 2, 3, 4], ndmin=5)
print(arr_fived)
print('shape of array :', arr_fived.shape) # Number of elements in each dimension.

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## NumPy Array Reshape

In [47]:
# Reshaping means changing the shape of an array.
# We can reshape as long as the elements required for reshaping are equal in both shapes.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3) # Creating a 4-Dimensions array (4 subarrays) with 3 elements each.
print(newarr)

arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr2 = arr2.reshape(2, 3, 2) # Creating a 2D array (2 subarrays) each subarray is a 3D array with 2 elements on each.
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## NumPy Array Iterating

In [48]:
arr = np.array([1, 2, 3])
for element in arr: #Iterating over the elements using for-each loop.
  print(element)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for subArr in arr2: # x = [1, 2, 3]
  for y in subArr:
    print(y)

1
2
3
1
2
3
4
5
6


## NumPy Joining Arrays

In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arrWhole = np.concatenate((arr1, arr2))
print("Arr Whole:", *arrWhole)

# Join two 2-D arrays along rows (axis=1):
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
arrJoinedByRows = np.concatenate((arr3, arr4), axis=1) #[1, 2, 5, 6] Elements of the first rows, [3, 4, 7, 8] Elements of the second rows.
print("arrays joined along rows: ", arrJoinedByRows)
arrJoinedByCols = np.concatenate((arr3, arr4), axis=0)
print("arrays joined along columns: ", arrJoinedByCols)

Arr Whole: 1 2 3 4 5 6
arrays joined along rows:  [[1 2 5 6]
 [3 4 7 8]]
arrays joined along columns:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## NumPy Array Split

In [55]:
# Splitting is the reverse operation of JOIN
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3) # Splitting the dataset into 3 different subarrays. 
# The return value is a list containing three arrays.
print(newarr)

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
#  returns three 2-D arrays, but they are split along the row (axis=1).
newarr2 = np.array_split(arr1, 3, axis=1)
print(newarr2)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Array Search

In [59]:
# search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

# There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
arr1 = np.array([6, 7, 8, 9])
x1 = np.searchsorted(arr1, 7)
print(x1)

# Search from right-side
arr2 = np.array([6, 7, 8, 9])
x2 = np.searchsorted(arr2, 7, side='right')
print(x2) # return the right most index instead.

# Multiple values search
arr3 = np.array([1, 3, 5, 7])
x3 = np.searchsorted(arr, [2, 4, 6]) # Find the indexes where the values 2, 4, and 6 should be inserted:
print(x3)

(array([3, 5, 6], dtype=int64),)
1
2
[1 3 7]


## NumPy Array Sort

In [60]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) # Sorted ascending

arr2 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr2))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]


## NumPy Array Filter

In [63]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr) #Only elements matched with TRUE

arr2 = np.array([41, 42, 43, 44])
filter_arr = arr2 > 42
newarr2 = arr2[filter_arr]
print(filter_arr)
print(newarr2)

arr3 = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr3 = arr3 % 2 == 0 # Even numbers
newarr3 = arr3[filter_arr3]
print(filter_arr)
print(newarr3)

[41 43]
[False False  True  True]
[43 44]
[False False  True  True]
[2 4 6]
